[package]
name = "bbc-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
futures = "0.3.31"
reqwest = "0.12.22"
scraper = "0.23.1"
serde = "1.0.219"
tokio = { version = "1.46.1", features = ["full"] }
